### ISSUE TITLE
[enhancement] Hide BossPoints for completed levels

### ISSUE THREAD

**Issue by steevokovsky** [StareInTheAir/dldu-points#1]
As a run progresses, some information about cleared levels become obsolete in my opinion. By adding another query parameter and a conditional rendering of BossPoints the user could choose to hide completed levels bosses. I don't think this would take long to implement, yet it would make the UI less convoluted in long runs. What's your opinion on this? (btw, I am not too familiar with Vue.js, so I don't know if my v-if would work like I intended)

Add new query param getter in [dldu-points/src/query-params.ts ](https://github.com/StareInTheAir/dldu-points/blob/2e7665e802e4781cf48cc9ed117eb42f3ef9d944/src/query-params.ts) (probably as a boolean):
```
function getHideCompletedBossList (): number | undefined {
  return getIntParam('hideCompletedBossList')
}
```

Import the new function in [dldu-points/src/App.vue](https://github.com/StareInTheAir/dldu-points/blob/586cfd02ab337ab67abeb315836f4d8cdf05d177/src/App.vue):

https://github.com/StareInTheAir/dldu-points/blob/586cfd02ab337ab67abeb315836f4d8cdf05d177/src/App.vue#L9

```
import { getSecondsPerPage, isSheetIdSuppliedAndValid, getHideCompletedBossList } from './query-params'
```

Add `getHideCompletedBossList` to data in [dldu-points/src/App.vue](https://github.com/StareInTheAir/dldu-points/blob/586cfd02ab337ab67abeb315836f4d8cdf05d177/src/App.vue):

https://github.com/StareInTheAir/dldu-points/blob/586cfd02ab337ab67abeb315836f4d8cdf05d177/src/App.vue#L22-L28

```
data: () => {
    return {
      dlduData: undefined as DlduData | undefined,
      errors: new Set<string>(),
      secondsPerPage: getSecondsPerPage() || 10,
      hideCompletedBossList : getHideCompletedBossList () || 0
    }
  },
```

In [dldu-points/src/components/LevelPoints.vue](https://github.com/StareInTheAir/dldu-points/blob/main/src/components/LevelPoints.vue):

https://github.com/StareInTheAir/dldu-points/blob/586cfd02ab337ab67abeb315836f4d8cdf05d177/src/components/LevelPoints.vue#L42-L46

```
<div v-if="achievedPoints < totalPoints && hideCompletedBossList ">
  <BossPoints
    v-for="boss in level.bosses"
    :key="level.name + boss.name"
    :boss="boss"
  />
</div>
```

**Comment by StareInTheAir** [comment]
Thanks for your suggestion. I also want to improve when which level and boss are shown. All information all the time is too much. I'm currently trying to figure out the best option, but it's challenging.

Bonjwa suggested hiding levels with no points. This would help in the early game, but not in the late game.
Your suggestion would help in the late game, but not the early game.

I'm testing current a further developed version of your suggestion: Only show bosses when levels are in progress. Levels are in progress when at least one boss is beaten, but not all bosses are beaten. This helps in early and late game, but when a level only has one boss, that boss is never shown, because that level can never be in progress.

If you or others have more ideas, please post them here.
